# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tapas/protos/annotated_text.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tapas.protos import interaction_pb2 as tapas_dot_protos_dot_interaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tapas/protos/annotated_text.proto',
  package='language.tapas',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!tapas/protos/annotated_text.proto\x12\x0elanguage.tapas\x1a\x1etapas/protos/interaction.proto\"\xf2\x01\n\rAnnotatedText\x12/\n\x0b\x61nnotations\x18\x01 \x03(\x0b\x32\x1a.language.tapas.Annotation2[\n\x16\x61nnotated_question_ext\x12\x18.language.tapas.Question\x18\xd6\xd7\x84\x91\x01 \x01(\x0b\x32\x1d.language.tapas.AnnotatedText2S\n\x12\x61nnotated_cell_ext\x12\x14.language.tapas.Cell\x18\xd6\xd7\x84\x91\x01 \x01(\x0b\x32\x1d.language.tapas.AnnotatedText\"\x88\x02\n\x15\x41nnotationDescription\x12M\n\x0c\x64\x65scriptions\x18\x01 \x03(\x0b\x32\x37.language.tapas.AnnotationDescription.DescriptionsEntry\x1a\x33\n\x11\x44\x65scriptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32k\n\x1b\x61nnotation_descriptions_ext\x12\x1b.language.tapas.Interaction\x18\xc3\xd4\xa6\x98\x01 \x01(\x0b\x32%.language.tapas.AnnotationDescription\"R\n\nAnnotation\x12\x18\n\x10\x62\x65gin_byte_index\x18\x01 \x01(\x03\x12\x16\n\x0e\x65nd_byte_index\x18\x02 \x01(\x03\x12\x12\n\nidentifier\x18\x03 \x01(\t'
  ,
  dependencies=[tapas_dot_protos_dot_interaction__pb2.DESCRIPTOR,])




_ANNOTATEDTEXT = _descriptor.Descriptor(
  name='AnnotatedText',
  full_name='language.tapas.AnnotatedText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='annotations', full_name='language.tapas.AnnotatedText.annotations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='annotated_question_ext', full_name='language.tapas.AnnotatedText.annotated_question_ext', index=0,
      number=304163798, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='annotated_cell_ext', full_name='language.tapas.AnnotatedText.annotated_cell_ext', index=1,
      number=304163798, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=328,
)


_ANNOTATIONDESCRIPTION_DESCRIPTIONSENTRY = _descriptor.Descriptor(
  name='DescriptionsEntry',
  full_name='language.tapas.AnnotationDescription.DescriptionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='language.tapas.AnnotationDescription.DescriptionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='language.tapas.AnnotationDescription.DescriptionsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=486,
)

_ANNOTATIONDESCRIPTION = _descriptor.Descriptor(
  name='AnnotationDescription',
  full_name='language.tapas.AnnotationDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='descriptions', full_name='language.tapas.AnnotationDescription.descriptions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='annotation_descriptions_ext', full_name='language.tapas.AnnotationDescription.annotation_descriptions_ext', index=0,
      number=319400515, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[_ANNOTATIONDESCRIPTION_DESCRIPTIONSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=595,
)


_ANNOTATION = _descriptor.Descriptor(
  name='Annotation',
  full_name='language.tapas.Annotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin_byte_index', full_name='language.tapas.Annotation.begin_byte_index', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_byte_index', full_name='language.tapas.Annotation.end_byte_index', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='identifier', full_name='language.tapas.Annotation.identifier', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=679,
)

_ANNOTATEDTEXT.fields_by_name['annotations'].message_type = _ANNOTATION
_ANNOTATIONDESCRIPTION_DESCRIPTIONSENTRY.containing_type = _ANNOTATIONDESCRIPTION
_ANNOTATIONDESCRIPTION.fields_by_name['descriptions'].message_type = _ANNOTATIONDESCRIPTION_DESCRIPTIONSENTRY
DESCRIPTOR.message_types_by_name['AnnotatedText'] = _ANNOTATEDTEXT
DESCRIPTOR.message_types_by_name['AnnotationDescription'] = _ANNOTATIONDESCRIPTION
DESCRIPTOR.message_types_by_name['Annotation'] = _ANNOTATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnnotatedText = _reflection.GeneratedProtocolMessageType('AnnotatedText', (_message.Message,), {
  'DESCRIPTOR' : _ANNOTATEDTEXT,
  '__module__' : 'tapas.protos.annotated_text_pb2'
  # @@protoc_insertion_point(class_scope:language.tapas.AnnotatedText)
  })
_sym_db.RegisterMessage(AnnotatedText)

AnnotationDescription = _reflection.GeneratedProtocolMessageType('AnnotationDescription', (_message.Message,), {

  'DescriptionsEntry' : _reflection.GeneratedProtocolMessageType('DescriptionsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ANNOTATIONDESCRIPTION_DESCRIPTIONSENTRY,
    '__module__' : 'tapas.protos.annotated_text_pb2'
    # @@protoc_insertion_point(class_scope:language.tapas.AnnotationDescription.DescriptionsEntry)
    })
  ,
  'DESCRIPTOR' : _ANNOTATIONDESCRIPTION,
  '__module__' : 'tapas.protos.annotated_text_pb2'
  # @@protoc_insertion_point(class_scope:language.tapas.AnnotationDescription)
  })
_sym_db.RegisterMessage(AnnotationDescription)
_sym_db.RegisterMessage(AnnotationDescription.DescriptionsEntry)

Annotation = _reflection.GeneratedProtocolMessageType('Annotation', (_message.Message,), {
  'DESCRIPTOR' : _ANNOTATION,
  '__module__' : 'tapas.protos.annotated_text_pb2'
  # @@protoc_insertion_point(class_scope:language.tapas.Annotation)
  })
_sym_db.RegisterMessage(Annotation)

_ANNOTATEDTEXT.extensions_by_name['annotated_question_ext'].message_type = _ANNOTATEDTEXT
tapas_dot_protos_dot_interaction__pb2.Question.RegisterExtension(_ANNOTATEDTEXT.extensions_by_name['annotated_question_ext'])
_ANNOTATEDTEXT.extensions_by_name['annotated_cell_ext'].message_type = _ANNOTATEDTEXT
tapas_dot_protos_dot_interaction__pb2.Cell.RegisterExtension(_ANNOTATEDTEXT.extensions_by_name['annotated_cell_ext'])
_ANNOTATIONDESCRIPTION.extensions_by_name['annotation_descriptions_ext'].message_type = _ANNOTATIONDESCRIPTION
tapas_dot_protos_dot_interaction__pb2.Interaction.RegisterExtension(_ANNOTATIONDESCRIPTION.extensions_by_name['annotation_descriptions_ext'])

_ANNOTATIONDESCRIPTION_DESCRIPTIONSENTRY._options = None
# @@protoc_insertion_point(module_scope)
