# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tapas/protos/negative_retrieval_examples.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tapas.protos import interaction_pb2 as tapas_dot_protos_dot_interaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tapas/protos/negative_retrieval_examples.proto',
  package='language.tapas',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.tapas/protos/negative_retrieval_examples.proto\x12\x0elanguage.tapas\x1a\x1etapas/protos/interaction.proto\"\xc9\x01\n\x19NegativeRetrievalExamples\x12:\n\x08\x65xamples\x18\x01 \x03(\x0b\x32(.language.tapas.NegativeRetrievalExample2p\n\x1fnegative_retrieval_examples_ext\x12\x18.language.tapas.Question\x18\xd0\xab\xe0\x89\x01 \x01(\x0b\x32).language.tapas.NegativeRetrievalExamples\"\xcd\x01\n\x18NegativeRetrievalExample\x12$\n\x05table\x18\x01 \x01(\x0b\x32\x15.language.tapas.Table\x12;\n\x04type\x18\x02 \x01(\x0e\x32-.language.tapas.NegativeRetrievalExample.Type\x12\x0c\n\x04rank\x18\x03 \x01(\x05\x12\r\n\x05score\x18\x04 \x01(\x02\"1\n\x04Type\x12\x0c\n\x08\x42\x41SELINE\x10\x01\x12\x0c\n\x08\x44OCUMENT\x10\x02\x12\r\n\tCORRUPTED\x10\x03'
  ,
  dependencies=[tapas_dot_protos_dot_interaction__pb2.DESCRIPTOR,])



_NEGATIVERETRIEVALEXAMPLE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='language.tapas.NegativeRetrievalExample.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BASELINE', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOCUMENT', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORRUPTED', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=459,
  serialized_end=508,
)
_sym_db.RegisterEnumDescriptor(_NEGATIVERETRIEVALEXAMPLE_TYPE)


_NEGATIVERETRIEVALEXAMPLES = _descriptor.Descriptor(
  name='NegativeRetrievalExamples',
  full_name='language.tapas.NegativeRetrievalExamples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='examples', full_name='language.tapas.NegativeRetrievalExamples.examples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='negative_retrieval_examples_ext', full_name='language.tapas.NegativeRetrievalExamples.negative_retrieval_examples_ext', index=0,
      number=288888272, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=300,
)


_NEGATIVERETRIEVALEXAMPLE = _descriptor.Descriptor(
  name='NegativeRetrievalExample',
  full_name='language.tapas.NegativeRetrievalExample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='language.tapas.NegativeRetrievalExample.table', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='language.tapas.NegativeRetrievalExample.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rank', full_name='language.tapas.NegativeRetrievalExample.rank', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='language.tapas.NegativeRetrievalExample.score', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NEGATIVERETRIEVALEXAMPLE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=508,
)

_NEGATIVERETRIEVALEXAMPLES.fields_by_name['examples'].message_type = _NEGATIVERETRIEVALEXAMPLE
_NEGATIVERETRIEVALEXAMPLE.fields_by_name['table'].message_type = tapas_dot_protos_dot_interaction__pb2._TABLE
_NEGATIVERETRIEVALEXAMPLE.fields_by_name['type'].enum_type = _NEGATIVERETRIEVALEXAMPLE_TYPE
_NEGATIVERETRIEVALEXAMPLE_TYPE.containing_type = _NEGATIVERETRIEVALEXAMPLE
DESCRIPTOR.message_types_by_name['NegativeRetrievalExamples'] = _NEGATIVERETRIEVALEXAMPLES
DESCRIPTOR.message_types_by_name['NegativeRetrievalExample'] = _NEGATIVERETRIEVALEXAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NegativeRetrievalExamples = _reflection.GeneratedProtocolMessageType('NegativeRetrievalExamples', (_message.Message,), {
  'DESCRIPTOR' : _NEGATIVERETRIEVALEXAMPLES,
  '__module__' : 'tapas.protos.negative_retrieval_examples_pb2'
  # @@protoc_insertion_point(class_scope:language.tapas.NegativeRetrievalExamples)
  })
_sym_db.RegisterMessage(NegativeRetrievalExamples)

NegativeRetrievalExample = _reflection.GeneratedProtocolMessageType('NegativeRetrievalExample', (_message.Message,), {
  'DESCRIPTOR' : _NEGATIVERETRIEVALEXAMPLE,
  '__module__' : 'tapas.protos.negative_retrieval_examples_pb2'
  # @@protoc_insertion_point(class_scope:language.tapas.NegativeRetrievalExample)
  })
_sym_db.RegisterMessage(NegativeRetrievalExample)

_NEGATIVERETRIEVALEXAMPLES.extensions_by_name['negative_retrieval_examples_ext'].message_type = _NEGATIVERETRIEVALEXAMPLES
tapas_dot_protos_dot_interaction__pb2.Question.RegisterExtension(_NEGATIVERETRIEVALEXAMPLES.extensions_by_name['negative_retrieval_examples_ext'])

# @@protoc_insertion_point(module_scope)
