# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tapas/protos/retriever_info.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tapas.protos import interaction_pb2 as tapas_dot_protos_dot_interaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tapas/protos/retriever_info.proto',
  package='language.tapas',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!tapas/protos/retriever_info.proto\x12\x0elanguage.tapas\x1a\x1etapas/protos/interaction.proto\"\x7f\n\rRetrieverInfo\x12\x0c\n\x04rank\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x01\x32Q\n\x0cquestion_ext\x12\x18.language.tapas.Question\x18\xe0\xb8\xdd\xa0\x01 \x01(\x0b\x32\x1d.language.tapas.RetrieverInfo'
  ,
  dependencies=[tapas_dot_protos_dot_interaction__pb2.DESCRIPTOR,])




_RETRIEVERINFO = _descriptor.Descriptor(
  name='RetrieverInfo',
  full_name='language.tapas.RetrieverInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rank', full_name='language.tapas.RetrieverInfo.rank', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='language.tapas.RetrieverInfo.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='question_ext', full_name='language.tapas.RetrieverInfo.question_ext', index=0,
      number=337075296, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['RetrieverInfo'] = _RETRIEVERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RetrieverInfo = _reflection.GeneratedProtocolMessageType('RetrieverInfo', (_message.Message,), {
  'DESCRIPTOR' : _RETRIEVERINFO,
  '__module__' : 'tapas.protos.retriever_info_pb2'
  # @@protoc_insertion_point(class_scope:language.tapas.RetrieverInfo)
  })
_sym_db.RegisterMessage(RetrieverInfo)

_RETRIEVERINFO.extensions_by_name['question_ext'].message_type = _RETRIEVERINFO
tapas_dot_protos_dot_interaction__pb2.Question.RegisterExtension(_RETRIEVERINFO.extensions_by_name['question_ext'])

# @@protoc_insertion_point(module_scope)
